export const MainSkills = [
    'JavaScript',
    'TypeScript',
    'HTML',
    'CSS',
    'React',
    'Redux',
    'LESS/SCSS/SASS',
    'StyledComponents',
    'Redux-Saga',
    'HTTP/HTTPS',
    'Rest-Api',
    'Material UI',
    'Git',
    'Scrum',
    'Jest',
];
